name: Aggregate Song Sheets Daily (JSONL)

on:
  schedule:
    - cron: "0 0 * * *"     # daily UTC
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: dataset-sync@ukulele-tuesday-datasets.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run dataset aggregation
        run: ./dataset-sync-scripts/song_sheets.py
        env:
          DST_PREFIX: ${{ github.event_name == 'pull_request' && format('song-sheets/aggregated/previews/pr-{0}', github.event.pull_request.number) || '' }}
