name: Synchronize Datasets

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sync-song-sheets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: dataset-sync@ukulele-tuesday-datasets.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run dataset aggregation
        run: ./dataset-sync.py --dataset song-sheets -o "song-sheets-data.jsonl" -o "gs://${DST_BUCKET}/${DST_PREFIX}/latest/data.jsonl" -o "gs://${DST_BUCKET}/${DST_PREFIX}/$(date +%Y-%m-%d)/data.jsonl"
        env:
          DST_BUCKET: ukulele-tuesday-datasets
          DST_PREFIX: ${{ github.event_name == 'pull_request' && format('song-sheets/aggregated/previews/pr-{0}', github.event.pull_request.number) || 'song-sheets/aggregated' }}

      - name: Validate song-sheets dataset
        run: python validate_datasets.py --dataset song-sheets --song-sheets-file song-sheets-data.jsonl

      - name: Upload song-sheets dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: song-sheets-dataset
          path: song-sheets-data.jsonl
          retention-days: 30

  sync-jam-sessions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: dataset-sync@ukulele-tuesday-datasets.iam.gserviceaccount.com
          # Add sheets scope for gspread
          scopes: https://www.googleapis.com/auth/spreadsheets.readonly

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run jam session plays sync
        run: ./dataset-sync.py --dataset jam-sessions -o "jam-sessions-data.jsonl" -o "gs://${DST_BUCKET}/${DST_PREFIX}/latest/data.jsonl" -o "gs://${DST_BUCKET}/${DST_PREFIX}/$(date +%Y-%m-%d)/data.jsonl"
        env:
          DST_BUCKET: ukulele-tuesday-datasets
          DST_PREFIX: ${{ github.event_name == 'pull_request' && format('jam-sessions/previews/pr-{0}', github.event.pull_request.number) || 'jam-sessions' }}

      - name: Validate jam-sessions dataset
        run: python validate_datasets.py --dataset jam-sessions --jam-sessions-file jam-sessions-data.jsonl

      - name: Upload jam-sessions dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jam-sessions-dataset
          path: jam-sessions-data.jsonl
          retention-days: 30
